import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import "./globals.css";
import BootstrapClient from "@/components/bootstrap-client";
import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Home - Remedium",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
                <Header/>
                {children}
            </body>
            <BootstrapClient/>
        </html>
    );
}